### ISSUE TITLE
More eye catching and pleasing button design 

### ISSUE THREAD

**Issue by dhruv-porwal** [ken1000minus7/YADA#31]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Issue Type : Adding Features

Please give a brief description of the feature you want to be added
Add rounded corners on buttons
# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dhruv-porwal** [comment]
Sir please assign this to me under pwoc

**Comment by yellowHatpro** [comment]
Ok, Good luck!

**Comment by dhruv-porwal** [comment]
Thank you sir 🙏

**Comment by yellowHatpro** [comment]
Closing this issue since I already merged one request for the same and added the pwoc tag to it. @dhruv-porwal please note that from next time onwards, create a single PR for a single feature, unlike this time when you made 2 PRs for a single feature. The former is considered a good practise, so do make it a habit in general.
