### ISSUE TITLE
Make readme more user friendly 

### ISSUE THREAD

**Issue by dhruv-porwal** [ken1000minus7/YADA#32]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Issue Type : Adding Features
Add comprehensive steps to make it easier for first time users to contribute 
Please give a brief description of the feature you want to be added

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dhruv-porwal** [comment]
Sir please assign this issue to me under pwoc

**Comment by yellowHatpro** [comment]
@dhruv-porwal, altho this issue is already open and assigned to someone else, #22 , I'll be assigning this to you because both of you are targeting different additions. For the next time, or while working on some more extensive projects, make sure there isn't any issue open for the same thing, or you can communicate with the maintainers first.

**Comment by dhruv-porwal** [comment]
OK sir.
Already made the pr please review.

**Comment by dhruv-porwal** [comment]
Sir please merge it

**Comment by yellowHatpro** [comment]
@dhruv-porwal I have merged the Pull Request
